spring.application.name=pedidos-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/db_pedidos
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

resilience4j.circuitbreaker.instances.kafka-pedidos.sliding-window-size=5
resilience4j.circuitbreaker.instances.kafka-pedidos.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafka-pedidos.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafka-pedidos.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.kafka-pedidos.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.kafka-pedidos.register-health-indicator=true

resilience4j.retry.instances.kafka-pedidos.max-attempts=3
resilience4j.retry.instances.kafka-pedidos.wait-duration=1s

management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always