spring.application.name=inventario-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventario-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.*

spring.sql.init.mode=always
resilience4j.circuitbreaker.instances.kafka-inventario.sliding-window-size=5
resilience4j.circuitbreaker.instances.kafka-inventario.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafka-inventario.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafka-inventario.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.kafka-inventario.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.kafka-inventario.register-health-indicator=true

resilience4j.retry.instances.kafka-inventario.max-attempts=3
resilience4j.retry.instances.kafka-inventario.wait-duration=1s
resilience4j.retry.instances.kafka-inventario.retry-exceptions=java.lang.RuntimeException

management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always